name: commandy
description: A modern Flutter package for managing asynchronous commands and state effectively.
version: 0.1.0+1
repository: https://github.com/Hapkiduki/commandy
issue_tracker: https://github.com/Hapkiduki/commandy/issues
topics: [commandy, state-management, command-pattern]
screenshots:
  - description: Commandy Logo.
    path: commandy_logo.png

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
